import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme/colors';

export const homeScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 18,
  },
  container: {
    gap: 18,
    width: '100%',
    maxWidth: 960,
    alignSelf: 'center',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  topBarSide: {
    width: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    justifyContent: 'center',
  },
  brandBadge: {
    width: 46,
    height: 46,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.border,
  },
  brandImage: {
    width: '100%',
    height: '100%',
  },
  brandTitle: {
    fontSize: 24,
    lineHeight: 28,
  },
  brandSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  topAction: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topActionPlus: {
    color: colors.text,
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(19, 8, 38, 0.55)',
    paddingHorizontal: 20,
  },
  modalCard: {
    gap: 14,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 20,
  },
  menuBackdrop: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    backgroundColor: 'rgba(10, 8, 14, 0.5)',
    paddingTop: 82,
    paddingRight: 16,
    paddingLeft: 56,
  },
  menuCard: {
    width: '100%',
    maxWidth: 300,
    gap: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 18,
  },
  menuHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    alignItems: 'flex-start',
  },
  menuProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  menuAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  menuAvatarLabel: {
    color: '#130A25',
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
  },
  menuProfileCopy: {
    gap: 2,
    flex: 1,
  },
  menuName: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '700',
  },
  menuHandle: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  menuActions: {
    gap: 10,
  },
  menuAction: {
    gap: 3,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  menuActionDanger: {
    borderColor: '#5A2A1E',
    backgroundColor: '#231310',
  },
  menuActionTitle: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  menuActionDangerTitle: {
    color: colors.accent,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  menuActionHint: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseLabel: {
    color: colors.accent,
    fontSize: 20,
    lineHeight: 20,
    fontWeight: '700',
  },
  modalSubtitle: {
    color: colors.textMuted,
  },
  modalActions: {
    gap: 10,
  },
  modalPrimaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  modalSecondaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  modalPrimaryIcon: {
    color: '#130A25',
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '700',
  },
  modalSecondaryIcon: {
    color: colors.accent,
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '700',
  },
  modalActionCopy: {
    flex: 1,
    gap: 2,
  },
  modalPrimaryLabel: {
    color: '#130A25',
    fontWeight: '700',
  },
  modalPrimaryHint: {
    color: '#4A3729',
    fontSize: 13,
    lineHeight: 18,
  },
  modalSecondaryLabel: {
    color: colors.accent,
    fontWeight: '700',
  },
  modalSecondaryHint: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  composerCard: {
    borderRadius: 28,
    padding: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 14,
  },
  composerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  composerHeader: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    flex: 1,
  },
  composerAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerAvatarText: {
    color: '#130A25',
    fontWeight: '700',
  },
  composerCopy: {
    flex: 1,
    gap: 4,
  },
  composerTitle: {
    color: colors.text,
  },
  composerSubtitle: {
    color: colors.textMuted,
  },
  composerCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerCloseLabel: {
    color: colors.accent,
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '700',
    textAlign: 'center',
  },
  composerFooter: {
    gap: 14,
  },
  composerHint: {
    color: colors.textMuted,
  },
  storiesContent: {
    gap: 14,
    paddingRight: 8,
  },
  storyItem: {
    alignItems: 'center',
    gap: 8,
  },
  storyRing: {
    width: 74,
    height: 74,
    borderRadius: 37,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceStrong,
  },
  storyCore: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyInitial: {
    color: colors.text,
    fontWeight: '800',
  },
  storyLabel: {
    fontSize: 13,
    lineHeight: 16,
  },
  feedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  feedTitle: {
    fontSize: 30,
    lineHeight: 34,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  filterText: {
    color: colors.accent,
    fontWeight: '700',
  },
  feedList: {
    gap: 18,
  },
  feedItemSpacer: {
    height: 18,
  },
  feedFooter: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSpacer: {
    height: 8,
  },
});
