import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme/colors';

export const newPostScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 14,
    paddingBottom: 28,
    gap: 14,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
  },
  closeLabel: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 18,
    fontWeight: '700',
  },
  headerCopy: {
    flex: 1,
    gap: 2,
  },
  headerEyebrow: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
  },
  headerSubcopy: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  postButton: {
    minWidth: 72,
    borderRadius: 10,
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postButtonDisabled: {
    opacity: 0.55,
  },
  postButtonLabel: {
    color: '#130A25',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '800',
  },
  heroCard: {
    overflow: 'hidden',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    minHeight: 246,
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 7, 15, 0.64)',
  },
  heroContent: {
    minHeight: 246,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 24,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 12,
  },
  heroActionPrimary: {
    borderRadius: 12,
    backgroundColor: colors.accent,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF7A12',
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  heroActionSecondary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#5A361E',
    backgroundColor: 'rgba(23, 19, 28, 0.88)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroActionPrimaryLabel: {
    color: '#130A25',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '800',
  },
  heroActionSecondaryLabel: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '700',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#C8BFCE',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLabel: {
    color: '#7D728B',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  sectionAction: {
    color: colors.accent,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
  },
  mediaInfoCard: {
    gap: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  mediaInfoTitle: {
    fontWeight: '700',
  },
  mediaInfoMeta: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  mediaInfoDescription: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  textArea: {
    minHeight: 118,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  loadingCard: {
    minHeight: 88,
    borderRadius: 18,
    backgroundColor: colors.surfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    padding: 12,
  },
  trailThumbnail: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#EFE7D7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailThumbnailLabel: {
    color: '#5C5242',
    fontWeight: '800',
  },
  trailCopy: {
    flex: 1,
    gap: 4,
  },
  trailTitle: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '700',
  },
  trailMeta: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  trailRegion: {
    color: colors.accent,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  clearTrailButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearTrailButtonLabel: {
    color: colors.accent,
    fontSize: 16,
    lineHeight: 16,
    fontWeight: '700',
  },
  emptyCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  emptyCardText: {
    color: colors.textMuted,
  },
  favoritePanel: {
    gap: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#3C2B1A',
    backgroundColor: '#17120F',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  favoritePanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  favoritePanelTitle: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  favoritePanelCopy: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    maxWidth: 220,
  },
  browseTrailsButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#5A361E',
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  browseTrailsButtonLabel: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
  },
  favoriteTrailList: {
    gap: 12,
  },
  favoriteTrailCard: {
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#2B221C',
    backgroundColor: '#13100D',
  },
  favoriteTrailCardActive: {
    borderColor: colors.accent,
    shadowColor: '#FF7A12',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  favoriteTrailImageWrap: {
    minHeight: 212,
    justifyContent: 'space-between',
    padding: 14,
  },
  favoriteTrailImage: {
    ...StyleSheet.absoluteFillObject,
  },
  favoriteTrailOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 8, 6, 0.42)',
  },
  favoriteTrailTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  favoriteTrailDistancePill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(17, 13, 9, 0.82)',
    borderWidth: 1,
    borderColor: '#5C4126',
  },
  favoriteTrailDistancePillText: {
    color: '#F8EEDF',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  favoriteTrailBottom: {
    gap: 4,
    marginTop: 'auto',
  },
  favoriteTrailTitle: {
    color: '#FFF4E9',
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '900',
  },
  favoriteTrailRegion: {
    color: '#D7C3AF',
    fontSize: 12,
    lineHeight: 16,
  },
  favoriteTrailStats: {
    flexDirection: 'row',
    gap: 1,
    backgroundColor: '#0F0D0B',
  },
  favoriteTrailStat: {
    flex: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#171310',
  },
  favoriteTrailStatLabel: {
    color: '#7D6F63',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  favoriteTrailStatValue: {
    color: '#F7EFE5',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  emptyFavoritesCard: {
    gap: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#3C2B1A',
    backgroundColor: '#1A1511',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  emptyFavoritesTitle: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '700',
  },
  emptyFavoritesCopy: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  emptyFavoritesButton: {
    alignSelf: 'flex-start',
    marginTop: 6,
    borderRadius: 999,
    backgroundColor: colors.accent,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  emptyFavoritesButtonLabel: {
    color: '#130A25',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 4,
  },
  statLabel: {
    color: '#7D728B',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  statValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  visibilityRow: {
    flexDirection: 'row',
    gap: 10,
  },
  visibilityChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    paddingVertical: 14,
  },
  visibilityChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  visibilityChipLabel: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
  },
  visibilityChipLabelActive: {
    color: '#130A25',
  },
});
