import { StyleSheet } from 'react-native';

import { colors } from '@/shared/theme/colors';

export const authScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#181A17',
  },
  keyboardArea: {
    flex: 1,
  },
  shell: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 14,
    justifyContent: 'center',
    backgroundColor: '#181A17',
  },
  glowTop: {
    position: 'absolute',
    top: 32,
    left: 36,
    right: 36,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(95, 138, 73, 0.1)',
  },
  card: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#3A3C37',
    backgroundColor: '#232522',
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 16,
  },
  registerCard: {
    borderColor: '#6A59FF',
    paddingHorizontal: 18,
    paddingVertical: 22,
  },
  logoBlock: {
    alignItems: 'center',
    gap: 6,
    paddingBottom: 8,
  },
  registerLogoBlock: {
    alignItems: 'flex-start',
    paddingBottom: 0,
  },
  logoMark: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'flex-end',
  },
  logoMarkColumn: {
    width: 5,
    height: 20,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  logoWordmark: {
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  registerWordmark: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: -0.5,
  },
  logoWordmarkWhite: {
    color: '#F4F1EC',
  },
  logoWordmarkAccent: {
    color: colors.accent,
  },
  logoTagline: {
    color: '#9E9489',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  headerRow: {
    alignItems: 'center',
  },
  registerHeaderRow: {
    alignItems: 'flex-start',
    gap: 6,
  },
  headerTitle: {
    color: '#EDE7DF',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
  },
  registerHeadline: {
    fontSize: 24,
    lineHeight: 28,
    textTransform: 'uppercase',
  },
  helperCopy: {
    color: '#A39A8F',
    fontSize: 12,
    lineHeight: 17,
  },
  registerSubtitle: {
    color: '#B3A89A',
    fontSize: 13,
    lineHeight: 18,
  },
  inputBlock: {
    gap: 8,
  },
  inputLabel: {
    color: '#E0D9CF',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  passwordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  passwordHint: {
    color: colors.accent,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#353733',
    backgroundColor: '#2A2C29',
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: '#F4F1EC',
    fontSize: 14,
    lineHeight: 18,
  },
  errorText: {
    color: '#FFB99A',
    fontSize: 12,
    lineHeight: 16,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  checkbox: {
    width: 14,
    height: 14,
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#6F6A63',
    backgroundColor: '#2A2C29',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: {
    borderColor: colors.accent,
    backgroundColor: '#332416',
  },
  checkboxDot: {
    width: 8,
    height: 8,
    backgroundColor: colors.accent,
  },
  termsText: {
    flex: 1,
    color: '#A39A8F',
    fontSize: 11,
    lineHeight: 16,
  },
  termsLink: {
    color: '#E7DDD0',
  },
  submitButton: {
    borderRadius: 12,
    backgroundColor: '#FF9B5A',
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF8A33',
    shadowOpacity: 0.32,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitLabel: {
    color: '#130A25',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '900',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#3B3D38',
  },
  dividerLabel: {
    color: '#8B8178',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
  },
  socialRow: {
    flexDirection: 'row',
    gap: 10,
  },
  socialButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#353733',
    backgroundColor: '#2A2C29',
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  socialLabel: {
    color: '#F4F1EC',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '800',
  },
  socialStatus: {
    color: '#8F857B',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingTop: 4,
  },
  footerLabel: {
    color: '#A39A8F',
    fontSize: 12,
    lineHeight: 16,
  },
  footerAction: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
});
